language: android
dist: trusty
jdk: oraclejdk11
android:
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    components:
        - build-tools-29.0.2
        - android-29
        - extra
before_install:
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "platforms;android-28"
matrix:
    fast_finish: true
    include:
        - name: "chech gradle"
          script: ./gradlew -v
        - name: "clean build"
          script: ./gradlew clean build