language: android
dist: trusty
jdk: oraclejdk11
android:
    components:
        - build-tools-29.0.2
        - android-29
        - extra
matrix:
    fast_finish: true
    include:
        - name: "chech gradle"
          script: ./gradlew build