language: android
dist: trusty
jdk: oraclejdk8
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=1.3.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git tag
- env
- git push -q https://${TAGPERM}@github.com/IIS-ZPI/ZPI2019_zaoczni_PIECIU_zamiast_300-stu
  --tags
deploy:
  provider: releases
  user: jnehlt
  password:
    secure: RleNFTgsBpmt5GrcqW3PtfAoEhqvjIdlxz1QaiH7F/+IcN4MDC8jYUfaL5FSMkc0I7GKysV0H4ja217CPElqAaKuQfTocWMCdYkUh4nbwL+TbKeVYBmFKkyVMKYcDaTf0OoW0C1EGUWQqphdj8TtUScFwq1N3mVPxAQOi45uF5H6rvnKmsawOat/4XvUvalfB+Q/H9UWemvyApfPfJyw8wddkE5VATW3Qku8/yoi5aQVnYnqouMnB2TVwIQBufU28YQQ703FVDEkkR9Vp4RNby6uUb8p8o5UJfZt/wdpx5ovunCiW4UQBjoy6QjS/6X4wV5qPuH+LZy4Ox3N3jZyUCfkq8UOk26DFMaK4SIhi5Rfqc+GOyXzJYEwNiXhyteCTYdla90kAGbc5xBRr/GVGnHqeOcsUeJbwa/b7pvUxWCUh4Sb7d1Kcdf022lwwppILe0r2RyXD55AnbmnQNU8Nv0fN/ImErjGZPEev+/dRFv2FQc2vMyheGWoSv4y+azN6dIRmwb2VUGcT8t+uG7hjRVkPEznXVc+CjFrPIoedguLwB0EXjK0cB4TwULaklwo7zX5EQNxPzVn8A7yUdrfhSLpl9EuWiSKADcjoUhVeYDaaMTGHM7vOAYspdjHTJaAgF6IqT3YakqquW5A6XOmaLduUbg+nnEM6apwIDpWXms=
  file: "./*.apk"
  skip_cleanup: true
  on:
    branch: CI_CD_improvements
matrix:
  fast_finish: true
  include:
  - name: DUMMY apk
    script:
    - touch ./test.apk
    - "./prepare_apk_name.sh"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: cJ92WRkMLbIk8pxPjSSfNjsZRhyocPGw6rzi7GnCF1lG+be+zo6gHs+oglD1RZA41iQDRzbEwEfUeIubAsX3J+nGbqruhb062RkOSQj2c1OrFhiMwklV9RCAtuLCP6yxFYXhcW7SLGe3+c+RRNP8b7qCVg+UEFLG9cUIPEYRu7YvYYtUJhkkOasn5aSl7bdduXRKr7g62Uxz0pI/o+y3l5jCd64HHYUG2Q53njlluzJexDq7wqsfYoEM+fKDKXhAfOLpyvMhlHnwuGL1vvBvP+iSkbfXYS2f2Fxsi0hd2og5k1sxa/vwltqsQfCAiLYlgc9WaCJGmfcMy6XBQmUcN7VoZA8QHRbP/uoQ0yc41Quk+r2H856XLexFy9vWDXjXNftF+YQWWDmIJMGFPOmEWbrz1OWA4K47A5eVpEu/GgDpFtEuRQjRKAKXBXwo/+0gq7VfB/xOs5qEK+guUvaBapJIn2Md0yoc/WTM2DbDzS8DvY5vyryZ6DTeU2Fta5KQznpFWVFnbjKRryGD99aNlQedbHuTmWd/23jFfEPTDpCwmXAXTRf+vqzhm9AcliDokDR59dbdzdgDj2u+J4jr2MeBdbz0XxAZrprC+bk1H/jr0C3yWe5Z1FvDa0R+RchXeivnxCQ4zExRifz+Fjv+GLPlqiqV97Ep1P1i4Ai8gec=
  - secure: qehgdUkG6qP7gFHPYg4ANzrUlptfH/3RBNOKs3ZiO3SLNcANxLesX0IZnvUL1Bkvi2i7tP4CPQ39fgjzbkhieagdyQ9M74ExOvR9/BHupvehy4p3yawgYXFJeSgOTvkli/sbTyJH7ZHoUGH3siWRWkG2B5nRqTDVKgKIIvlBEGYz8x2Efu1zmto6hk74wLP+sq36BEmE42pT92UaIhQcfYhBDDAZpgiyKUX8Mxg7qB6cADXbqfPSyQ0l4qip7CBmCLRIcr9jlBBOAgjBx1Qs1cIoNpCd7It9sDfflvQTLklQumBCtZLsJ7z7h4nGTaHKrw5pFKR5YfGd/BouasrEh5VdjlCfhljoJaDpkZN2a1XWXYG8N/L23Z8MWAUnlUJUuc71XXUakRM6uBDPX/pwRx9IjkpWuLUtp6n/XtM5mDlK4JlbdJfxUUANA3askMwVjhG1X21b4iLyxxgC586qOdjSD8hDPDZ0HtTEpfc+b5ALHuvFJ5NHNgaRdgcJU9Zg/VkRAkTRHGqvywYK7Bn4Z6cOfM9Abrvchw9D17a6C0/KwVgsIXvqC3CWPtduwnb1e4+M5wN589W6yruhIxytB/sS9ihiViA30EHMdsuoPUXn/IQPfzUS4g2lc9P2qRh/6vC8gSuGEdCmMTngMmksmedD3lzOhbVEMBUtuYkjqaU=
