language: android
dist: trusty
android:
    components:
        - tools
        - platform-tools
        - build-tools-26.0.1
        - android-26
        - extra
matrix:
    fast_finish: true
    include:
        - name: "chech gradle"
          script: ./gradlew build