language: android
dist: trusty
jdk: oraclejdk11
android:
    components:
        - build-tools-26.0.1
        - android-26
        - extra
matrix:
    fast_finish: true
    include:
        - name: "chech gradle"
          script: ./gradlew build