language: android
dist: trusty
jdk: oraclejdk8
android:
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    components:
        - build-tools-29.0.2
        - android-29
        - extra
matrix:
    fast_finish: true
    include:
        - name: "chech gradle"
          script: ./gradlew -v
        - name: "clean build"
          script: ./gradlew clean build